app = "lafavape"
primary_region = "hkg"
  vm_size = "shared-cpu-1x"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
